FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Jquintino 




## Comandas [/comanda]

É uma api que controla uma comanda de um restaurante

### Lista todas as comandas [GET]

+ Response 200 (application/json)

        [
             {
                "id": 1,
                "mesa": "mesa 1",
                "estado": "1",
                "timestamp": "2020-07-03T02:30:17.000Z",
                "produtos": [
                    {
                        "id": 1,
                        "qtd": 2,
                        "id_produto": {
                            "id": 1,
                            "desc": "Refri",
                            "preco": 2.5
                        }
                    },
                    {
                        "id": 8,
                        "qtd": 1,
                        "id_produto": {
                            "id": 3,
                            "desc": "Cerva",
                            "preco": 3.89
                        }
                    },
                    {
                        "id": 15,
                        "qtd": 2,
                        "id_produto": {
                            "id": 4,
                            "desc": "Batata Frita",
                            "preco": 15
                        }
                    }
                ]
            },
            {
                "id": 3,
                "mesa": "Mesa 2",
                "estado": "1",
                "timestamp": "2020-07-09T03:31:55.000Z",
                "produtos": [
                    {
                        "id": 13,
                        "qtd": 3,
                        "id_produto": {
                            "id": 3,
                            "desc": "Cerva",
                            "preco": 3.89
                        }
                    },
                    {
                        "id": 14,
                        "qtd": 1,
                        "id_produto": {
                            "id": 1,
                            "desc": "Refri",
                            "preco": 2.5
                        }
                    }
                ]
            }
        ]

### Cadastrar comanda [POST]

+ Request
        
        [
            {
                "mesa":"Mesa 43",
                "estado":"Ativo"
            }
        ]

+ Response 204 (application/json)


## Gerenciar a comanda [/comanda/{id_comanda}]

### Ver comanda [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "mesa": "mesa 1",
                "estado": "1",
                "timestamp": "2020-07-03T02:30:17.000Z",
                "produtos": [
                    {
                        "id": 1,
                        "qtd": 2,
                        "id_produto": {
                            "id": 1,
                            "desc": "Refri",
                            "preco": 2.5
                        }
                    },
                    {
                        "id": 8,
                        "qtd": 1,
                        "id_produto": {
                            "id": 3,
                            "desc": "Cerva",
                            "preco": 3.89
                        }
                    },
                    {
                        "id": 15,
                        "qtd": 2,
                        "id_produto": {
                            "id": 4,
                            "desc": "Batata Frita",
                            "preco": 15
                        }
                    }
                ]
            }
        ]

### Atualizar Comanda[PUT]


+ Request
        
        [
            {
                "mesa":"Mesa 42",
                "estado":"0"
            }
        ]

+ Response 204 (application/json)

### Excluir comanda[DELETE]

+ Response 204 (application/json)

## Produtos na comanda [/produtoComandas]

### Visualizar produtos da comanda[GET]

+ Response 201 (application/json)

        [
            {
                "id": 1,
                "qtd": 2,
                "timestamp": "2020-07-07T00:11:45.000Z",
                "id_produto": {
                    "id": 1,
                    "desc": "Refri",
                    "preco": 2.5
                }
            },
            {
                "id": 8,
                "qtd": 1,
                "timestamp": "2020-07-12T02:24:11.000Z",
                "id_produto": {
                    "id": 3,
                    "desc": "Cerva",
                    "preco": 3.89
                }
            }
        ]

        
### Adicionar produto na comanda [POST]

+ Request (application/json)

        [
            {
              "id_comanda":"1"
              "id_produto":"55",
              "qtd":"1"
            }
        ]
    

+ Response 200 (application/json)

## Gerenciar produtos na comanda [/produtoComanda/{id_comanda}]

### Ver produto da comanda [GET]

+ Response 201 (application/json)

        [
             {
                "id": 1,
                "qtd": 2,
                "timestamp": "2020-07-07T00:11:45.000Z",
                "id_produto": {
                    "id": 1,
                    "desc": "Refri",
                    "preco": 2.5
                }
            }
        ]

### Atualizar produto Comanda[PUT]


+ Request
        
        [
            {
                "numero_produto":"1",
                "Qtd":"3"
            }
        ]

+ Response 204 (application/json)

### Excluir produto comanda[DELETE]

+ Response 204 (application/json)


## Produtos [/produto]

### Visualizar todos os produtos[GET]

+ Response 201 (application/json)

        [
            {
                "id_produto":"55",
                "desc":"Refri",
                "preco":"2.00"
            },
            {
                "id_produto":"66",
                "desc":"Batatinhas",
                "preco":"20.00"
            }
        ]
        
### Adicionar produto [POST]

+ Request (application/json)

        [
            {
                "desc":"Petisco",
                "preco":"30.00"
            }
        ]
    

+ Response 204 (application/json)


## Gerenciar Produto [/produto/{id}]

### Ver produto [GET]

+ Response 201 (application/json)

        [
            {
                "desc":"Refri",
                "preco":"2.00"
            }
        ]


### Atualizar produto[PUT]


+ Request
        
        [
            {
                "desc":"Refri - Coca-cola",
                "preco":"2.50"
            }
        ]

+ Response 204 (application/json)

### Excluir comanda[DELETE]

+ Response 204 (application/json)